### ISSUE TITLE
postWebMessage failed

### ISSUE THREAD

**Issue by summanzhao** [jnschulze/flutter-webview-windows#277]
Hello, I would like to send a message to JavaScript using the postWebMessage method:

WebviewController kWebController=WebviewController();

//Several initialization tasks for WebWiew
........
_ Subscriptions. add (kWebController. loadingState. listen ((state)){

DebugPrint ('Loading state: $state ');

If (state==LoadingState. navigation Completed){

KWebController.executeScript（

"Window. addEventListener ('message ', event=>{console. log ('Received message:', event. data);});";

KWebController. postWebMessage ("hello world");

}

});

After completion

KWebController. postWebMessage ("hello world");

There was an error in this call:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(not_supported, Posting the message failed., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>

How should I solve it? Looking forward to your reply!

**Comment by bladeofgod** [comment]
same issue.  
And can you post msg from web ?
